services:
  - type: web
    name: lerelais-app
    env: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false # À remplir avec l'URL de Supabase
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
